In [1]:
import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F
import itertools
import numpy as np
import scipy.sparse as sp
from model import Model
#import pygraphviz as pgv
import dgl.nn as dglnn
import dgl.function as fn
from train_gsData import *
from test_gsData import *
from hetDotProduct import HeteroDotProductPredictor
from sklearn.metrics import roc_auc_score
from rgcnClass import RGCN

Using backend: pytorch

C:\Users\Jayant\Anaconda3\lib\site-packages\dgl\nn\pytorch\__init__.py
src2369
dest2369
C:\Users\Jayant\Anaconda3\lib\site-packages\dgl\nn\pytorch\__init__.py

In [2]:
train = train_hetero_graph
test = test_hetero_graph

In [3]:
sampling_rate = 1
epochs = 400

In [4]:
def construct_negative_graph(graph, k, etype):
    utype, _, vtype = etype
    src, dst = graph.edges(etype=etype)
    torch.random.manual_seed(1)
    
    neg_src = src.repeat_interleave(k)
    neg_dst = torch.randint(0, graph.num_nodes(vtype), (len(src) * k,))
    return dgl.heterograph(
        {etype: (neg_src, neg_dst)},
        num_nodes_dict={ntype: graph.num_nodes(ntype) for ntype in graph.ntypes})

def compute_loss(pos_score, neg_score):
    # Margin loss
    n_edges = pos_score.shape[0]
    return (1 - pos_score.unsqueeze(1) + neg_score.view(n_edges, -1)).clamp(min=0).mean()


def manual_auc(scores,labels):
    s = []
    p = []
    for i in range(len(scores)):
        s.append((scores[i])[0])
    l = labels.tolist()
    '''print("SCORES LENGTH: ",len(s))
    print(s)
    print("LABELS LENGTH: ",len(l))
    print(l)'''
    I = 0
    for i in range(len(l)):
        if l[i]==0:
            I = i
            break
    D = I * sampling_rate * I
    np = I
    nn = sampling_rate*I
    counter = 0
    for i in range(np):
        percent = 0
        for j in range(np,np+nn):
            #print("j = ",j)
            if s[i]>s[j]:  
                percent = percent+1
                counter = counter+1
        #print("---------- Positive sample is greater than ",percent/nn," number of negative samples")
        p.append(percent/nn)
        percent = 0
    #print("AUC MANUAL: ",counter/D)
    return p

def compute_auc(pos_score, neg_score):
    scores = torch.cat([pos_score, neg_score]).numpy()
    labels = torch.cat(
        [torch.ones(pos_score.shape[0]), torch.zeros(neg_score.shape[0])]).numpy()
    p=manual_auc(scores,labels)
    return roc_auc_score(labels, scores),p

In [5]:
train_neg = construct_negative_graph(train, sampling_rate, ('judgement', 'similarTo', 'judgement'))
test_neg = construct_negative_graph(test,sampling_rate,('judgement', 'similarTo', 'judgement'))
print(train.etypes)
model = Model(85, 10, 2, train.etypes)
judgement_feats = train.nodes['judgement'].data['feature']
test_judgement_feats = test.nodes['judgement'].data['feature']
node_features = {'judgement': judgement_feats}#, 'court': court_feats}
test_node_features = {'judgement': test_judgement_feats}
optimizer = torch.optim.Adam(model.parameters())
pred = HeteroDotProductPredictor()

tensor(803)
tensor(947)
tensor(803)
tensor(947)
['similarTo']

In [6]:
for epoch in range(epochs):
    h = model(train,train_neg,node_features,etype='similarTo')
    pos_score = pred(train, h, etype='similarTo')
    #print(len(pos_score))
    neg_score = pred(train_neg, h, etype='similarTo')
    #print(len(neg_score))
    # backward
    optimizer.zero_grad()
    loss = compute_loss(pos_score, neg_score)
    loss.backward()
    optimizer.step()

    print('In epoch {}'.format(epoch))

In epoch 0
In epoch 1
In epoch 2
In epoch 3
In epoch 4
In epoch 5
In epoch 6
In epoch 7
In epoch 8
In epoch 9
In epoch 10
In epoch 11
In epoch 12
In epoch 13
In epoch 14
In epoch 15
In epoch 16
In epoch 17
In epoch 18
In epoch 19
In epoch 20
In epoch 21
In epoch 22
In epoch 23
In epoch 24
In epoch 25
In epoch 26
In epoch 27
In epoch 28
In epoch 29
In epoch 30
In epoch 31
In epoch 32
In epoch 33
In epoch 34
In epoch 35
In epoch 36
In epoch 37
In epoch 38
In epoch 39
In epoch 40
In epoch 41
In epoch 42
In epoch 43
In epoch 44
In epoch 45
In epoch 46
In epoch 47
In epoch 48
In epoch 49
In epoch 50
In epoch 51
In epoch 52
In epoch 53
In epoch 54
In epoch 55
In epoch 56
In epoch 57
In epoch 58
In epoch 59
In epoch 60
In epoch 61
In epoch 62
In epoch 63
In epoch 64
In epoch 65
In epoch 66
In epoch 67
In epoch 68
In epoch 69
In epoch 70
In epoch 71
In epoch 72
In epoch 73
In epoch 74
In epoch 75
In epoch 76
In epoch 77
In epoch 78
In epoch 79
In epoch 80
In epoch 81
In epoch 82
In epoch 83
In epoch 84
In epoch 85
In epoch 86
In epoch 87
In epoch 88
In epoch 89
In epoch 90
In epoch 91
In epoch 92
In epoch 93
In epoch 94
In epoch 95
In epoch 96
In epoch 97
In epoch 98
In epoch 99

In [7]:
with torch.no_grad():
    pos_score = pred(test, h, etype='similarTo')
    neg_score = pred(test_neg, h, etype='similarTo')
    #node_embeddings = model.sage(test,test_node_features)
    #torch.save(node_embeddings , 'similarity_node_embeddings.pt')
    score,p = compute_auc(pos_score, neg_score)
    #score contains the AUC of predefined function
    #p contains the AUC computed by manual AUC
    print('AUC',score )
    index=[]
    neg_index=[]
    scores=[]
    neg_scores=[]
    for i in range(len(p)):
        if p[i] > sum(p)/len(p):
            index.append(i)
            scores.append(p[i])
        else:
            neg_index.append(i)
            neg_scores.append(p[i])
    #print("INDICES: ",index)
    #print("SCORES: ",scores)
    data = pd.read_csv("input/TEST_SET.csv")
    predicted = pd.DataFrame(columns=['SUBJECT','RELATION','OBJECT','SCORE'])
    not_predicted = pd.DataFrame(columns=['SUBJECT','RELATION','OBJECT','SCORE'])
    print("-------- Predicted Edges ---------")
    for i in range(len(index)):
        print("-------------- POSITIVE SAMPLES")
        print(data.loc[index[i],:])
        predicted.loc[i,'SUBJECT'] = data.loc[index[i],'SUBJECT']
        predicted.loc[i,'RELATION'] = data.loc[index[i],'RELATION']
        predicted.loc[i,'OBJECT'] = data.loc[index[i],'OBJECT']
        predicted.loc[i,'SCORE'] = scores[i]
    for i in range(len(neg_index)):
        print("--------------- NEGATIVE SAMPLES")
        print(data.loc[neg_index[i],:])
        not_predicted.loc[i,'SUBJECT'] = data.loc[neg_index[i],'SUBJECT']
        not_predicted.loc[i,'RELATION'] = data.loc[neg_index[i],'RELATION']
        not_predicted.loc[i,'OBJECT'] = data.loc[neg_index[i],'OBJECT']
        not_predicted.loc[i,'SCORE'] = neg_scores[i]
    predicted = predicted.drop_duplicates().reset_index(drop=True)
    not_predicted = not_predicted.drop_duplicates().reset_index(drop=True)
    predicted.to_csv("output/predicted_results.csv",index=False)  #remove NEG later !!!!
    not_predicted.to_csv("output/not_predicted_results.csv",index=False)  #remove NEG later !!!

AUC 0.7389399657044382
-------- Predicted Edges ---------
-------------- POSITIVE SAMPLES
SUBJECT           803
RELATION    similarTo
OBJECT            106
Name: 0, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           803
RELATION    similarTo
OBJECT            106
Name: 1, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            675
Name: 2, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           411
RELATION    similarTo
OBJECT            818
Name: 3, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           407
RELATION    similarTo
OBJECT            839
Name: 4, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            298
Name: 5, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           103
RELATION    similarTo
OBJECT            799
Name: 6, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           499
RELATION    similarTo
OBJECT            810
Name: 7, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           844
RELATION    similarTo
OBJECT            940
Name: 8, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           863
RELATION    similarTo
OBJECT            943
Name: 10, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            118
Name: 11, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           223
RELATION    similarTo
OBJECT            855
Name: 12, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           819
RELATION    similarTo
OBJECT            307
Name: 14, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            369
Name: 15, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           822
RELATION    similarTo
OBJECT            124
Name: 16, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            299
Name: 17, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            489
Name: 18, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           350
RELATION    similarTo
OBJECT            804
Name: 20, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           869
RELATION    similarTo
OBJECT             73
Name: 22, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT          1028
RELATION    similarTo
OBJECT            958
Name: 23, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            602
Name: 26, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           668
RELATION    similarTo
OBJECT            840
Name: 28, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            144
Name: 29, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           851
RELATION    similarTo
OBJECT             77
Name: 31, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           824
RELATION    similarTo
OBJECT              1
Name: 32, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            55
RELATION    similarTo
OBJECT            873
Name: 33, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            551
Name: 34, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           873
RELATION    similarTo
OBJECT            556
Name: 35, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT            122
Name: 37, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           803
RELATION    similarTo
OBJECT            506
Name: 39, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           210
RELATION    similarTo
OBJECT            805
Name: 42, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           804
RELATION    similarTo
OBJECT            944
Name: 43, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            422
Name: 44, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           885
RELATION    similarTo
OBJECT             98
Name: 46, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           832
RELATION    similarTo
OBJECT            105
Name: 47, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           452
RELATION    similarTo
OBJECT            804
Name: 48, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           755
RELATION    similarTo
OBJECT            859
Name: 49, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            931
Name: 50, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           769
RELATION    similarTo
OBJECT            814
Name: 53, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            80
RELATION    similarTo
OBJECT            826
Name: 56, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           191
RELATION    similarTo
OBJECT            818
Name: 57, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           646
RELATION    similarTo
OBJECT            840
Name: 58, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           825
RELATION    similarTo
OBJECT            408
Name: 60, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            481
Name: 61, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           291
RELATION    similarTo
OBJECT            804
Name: 62, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            627
Name: 64, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           178
RELATION    similarTo
OBJECT            814
Name: 65, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           845
RELATION    similarTo
OBJECT            760
Name: 68, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           859
RELATION    similarTo
OBJECT            108
Name: 70, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            920
Name: 72, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           807
RELATION    similarTo
OBJECT             49
Name: 73, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           647
RELATION    similarTo
OBJECT            799
Name: 75, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           772
RELATION    similarTo
OBJECT            808
Name: 77, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           822
RELATION    similarTo
OBJECT            740
Name: 80, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT              6
Name: 81, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           946
RELATION    similarTo
OBJECT            859
Name: 82, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           862
RELATION    similarTo
OBJECT            206
Name: 83, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           837
RELATION    similarTo
OBJECT            904
Name: 84, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            112
Name: 85, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           392
RELATION    similarTo
OBJECT            798
Name: 86, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            571
Name: 87, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           882
RELATION    similarTo
OBJECT            701
Name: 89, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           818
RELATION    similarTo
OBJECT              0
Name: 90, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           809
RELATION    similarTo
OBJECT            577
Name: 92, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           258
RELATION    similarTo
OBJECT            824
Name: 93, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           613
RELATION    similarTo
OBJECT            804
Name: 96, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           812
RELATION    similarTo
OBJECT            190
Name: 97, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            531
Name: 98, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            261
Name: 101, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           875
RELATION    similarTo
OBJECT            386
Name: 103, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            646
Name: 104, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           899
RELATION    similarTo
OBJECT            852
Name: 105, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           202
RELATION    similarTo
OBJECT            873
Name: 108, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           811
RELATION    similarTo
OBJECT            916
Name: 109, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           820
RELATION    similarTo
OBJECT            544

Name: 110, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT             66
Name: 111, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           802
RELATION    similarTo
OBJECT            495
Name: 112, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           571
RELATION    similarTo
OBJECT            848
Name: 116, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            719
Name: 117, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           869
RELATION    similarTo
OBJECT            197
Name: 118, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           318
RELATION    similarTo
OBJECT            855
Name: 120, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           808
RELATION    similarTo
OBJECT            645
Name: 122, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           433
RELATION    similarTo
OBJECT            870
Name: 124, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           204
RELATION    similarTo
OBJECT            863
Name: 126, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           813
RELATION    similarTo
OBJECT            503
Name: 127, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           187
RELATION    similarTo
OBJECT            856
Name: 128, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           851
RELATION    similarTo
OBJECT            296
Name: 129, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           880
RELATION    similarTo
OBJECT            566
Name: 131, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            743
Name: 132, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            92
RELATION    similarTo
OBJECT            848
Name: 134, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            552
Name: 135, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           327
RELATION    similarTo
OBJECT            802
Name: 136, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           855
RELATION    similarTo
OBJECT            418
Name: 137, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           367
RELATION    similarTo
OBJECT            819
Name: 138, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            36
RELATION    similarTo
OBJECT            833
Name: 139, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           249
RELATION    similarTo
OBJECT            856
Name: 140, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           817
RELATION    similarTo
OBJECT             18
Name: 142, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           497
RELATION    similarTo
OBJECT            814
Name: 143, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           869
RELATION    similarTo
OBJECT             29
Name: 144, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           446
RELATION    similarTo
OBJECT            855
Name: 147, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            906
Name: 149, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           794
RELATION    similarTo
OBJECT            848
Name: 153, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           864
RELATION    similarTo
OBJECT            328
Name: 154, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           681
RELATION    similarTo
OBJECT            861
Name: 155, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            305
Name: 156, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           855
RELATION    similarTo
OBJECT            110
Name: 157, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           915
RELATION    similarTo
OBJECT            825
Name: 159, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           135
RELATION    similarTo
OBJECT            808
Name: 160, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           825
RELATION    similarTo
OBJECT            356
Name: 161, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           824
RELATION    similarTo
OBJECT            532
Name: 162, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           847
RELATION    similarTo
OBJECT            363
Name: 164, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           391
RELATION    similarTo
OBJECT            821
Name: 165, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT             89
Name: 169, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           984
RELATION    similarTo
OBJECT            981
Name: 170, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           140
RELATION    similarTo
OBJECT            852
Name: 171, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT          1015
RELATION    similarTo
OBJECT           1025
Name: 172, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           802
RELATION    similarTo
OBJECT            754
Name: 173, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            784
Name: 174, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           981
RELATION    similarTo
OBJECT            972
Name: 175, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           814
RELATION    similarTo
OBJECT            153
Name: 176, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           793
RELATION    similarTo
OBJECT            818
Name: 177, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            746
Name: 178, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            782
Name: 179, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           812
RELATION    similarTo
OBJECT             30
Name: 180, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           847
RELATION    similarTo
OBJECT            279
Name: 181, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            198
Name: 182, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           809
RELATION    similarTo
OBJECT             68
Name: 183, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           864
RELATION    similarTo
OBJECT            864
Name: 184, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           825
RELATION    similarTo
OBJECT            731
Name: 185, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           835
RELATION    similarTo
OBJECT            904
Name: 186, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           965
RELATION    similarTo
OBJECT            273
Name: 187, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           844
RELATION    similarTo
OBJECT            820
Name: 188, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           818
RELATION    similarTo
OBJECT            259
Name: 189, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           819
RELATION    similarTo
OBJECT            402
Name: 190, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           822
RELATION    similarTo
OBJECT            582
Name: 191, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           814
RELATION    similarTo
OBJECT            178
Name: 192, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           804
RELATION    similarTo
OBJECT            698
Name: 193, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           865
RELATION    similarTo
OBJECT            576
Name: 194, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           821
RELATION    similarTo
OBJECT            654
Name: 195, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT          1019
RELATION    similarTo
OBJECT            960
Name: 196, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           852
RELATION    similarTo
OBJECT            605
Name: 197, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           750
RELATION    similarTo
OBJECT            833
Name: 198, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            437
Name: 200, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           868
RELATION    similarTo
OBJECT             88
Name: 201, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           813
RELATION    similarTo
OBJECT            141
Name: 202, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           820
RELATION    similarTo
OBJECT            835
Name: 203, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           853
RELATION    similarTo
OBJECT            908
Name: 204, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           829
RELATION    similarTo
OBJECT            835
Name: 206, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           850
RELATION    similarTo
OBJECT            168
Name: 207, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           105
RELATION    similarTo
OBJECT            832
Name: 208, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           833
RELATION    similarTo
OBJECT            233
Name: 209, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           815
RELATION    similarTo
OBJECT            904
Name: 210, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           808
RELATION    similarTo
OBJECT            200
Name: 211, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           882
RELATION    similarTo
OBJECT            186
Name: 212, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           818
RELATION    similarTo
OBJECT            237
Name: 214, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            857
Name: 217, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           804
RELATION    similarTo
OBJECT            295
Name: 218, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           861
RELATION    similarTo
OBJECT            512
Name: 224, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           277
RELATION    similarTo
OBJECT            839
Name: 226, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            547
Name: 227, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            448
Name: 229, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           894
RELATION    similarTo
OBJECT            825
Name: 232, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           834
RELATION    similarTo
OBJECT            587
Name: 233, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           480
RELATION    similarTo
OBJECT            814
Name: 234, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           286
RELATION    similarTo
OBJECT            818
Name: 239, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           650
RELATION    similarTo
OBJECT            819

Name: 240, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            835
Name: 241, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            794
Name: 242, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           215
RELATION    similarTo
OBJECT            833
Name: 245, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           807
RELATION    similarTo
OBJECT            632
Name: 246, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            128
Name: 247, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            781
Name: 248, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           820
RELATION    similarTo
OBJECT            815
Name: 249, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           850
RELATION    similarTo
OBJECT            303
Name: 250, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           985
RELATION    similarTo
OBJECT           1001
Name: 251, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           659
RELATION    similarTo
OBJECT            839
Name: 255, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           851
RELATION    similarTo
OBJECT            616
Name: 256, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           113
RELATION    similarTo
OBJECT            808
Name: 257, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT          1002
RELATION    similarTo
OBJECT            981
Name: 258, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            217
Name: 259, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           800
RELATION    similarTo
OBJECT            931
Name: 261, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           835
RELATION    similarTo
OBJECT            829
Name: 263, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           818
RELATION    similarTo
OBJECT            191
Name: 264, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            304
Name: 267, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           832
RELATION    similarTo
OBJECT            453
Name: 270, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           818
RELATION    similarTo
OBJECT            789
Name: 271, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT             90
Name: 273, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           800
RELATION    similarTo
OBJECT            840
Name: 276, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           634
RELATION    similarTo
OBJECT            825
Name: 278, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            478
Name: 280, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           100
RELATION    similarTo
OBJECT            855
Name: 281, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           451
RELATION    similarTo
OBJECT            873
Name: 282, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           930
RELATION    similarTo
OBJECT            870
Name: 283, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            904
Name: 284, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           331
RELATION    similarTo
OBJECT            856
Name: 285, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           852
RELATION    similarTo
OBJECT             54
Name: 291, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           975
RELATION    similarTo
OBJECT            997
Name: 292, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           803
RELATION    similarTo
OBJECT            211
Name: 294, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            116
Name: 295, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           861
RELATION    similarTo
OBJECT            393
Name: 296, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           824
RELATION    similarTo
OBJECT            567
Name: 297, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           808
RELATION    similarTo
OBJECT            945
Name: 299, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           522
RELATION    similarTo
OBJECT            846
Name: 301, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            216
Name: 303, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            158
Name: 304, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           514
RELATION    similarTo
OBJECT            806
Name: 307, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           627
RELATION    similarTo
OBJECT            846
Name: 308, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           344
RELATION    similarTo
OBJECT            878
Name: 309, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           110
RELATION    similarTo
OBJECT            855
Name: 310, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           859
RELATION    similarTo
OBJECT            688
Name: 311, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            172
Name: 313, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT          1016
RELATION    similarTo
OBJECT           1025
Name: 315, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           264
RELATION    similarTo
OBJECT            817
Name: 318, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           435
RELATION    similarTo
OBJECT            805
Name: 320, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           858
RELATION    similarTo
OBJECT            663
Name: 322, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           829
RELATION    similarTo
OBJECT            857
Name: 323, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           863
RELATION    similarTo
OBJECT            657
Name: 324, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           878
RELATION    similarTo
OBJECT            542
Name: 326, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           728
RELATION    similarTo
OBJECT            813
Name: 327, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           819
RELATION    similarTo
OBJECT            678
Name: 328, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            820
Name: 329, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            60
RELATION    similarTo
OBJECT            814
Name: 330, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           562
RELATION    similarTo
OBJECT            852
Name: 331, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            500
Name: 333, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           795
RELATION    similarTo
OBJECT            802
Name: 335, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           845
RELATION    similarTo
OBJECT            664
Name: 336, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           832
RELATION    similarTo
OBJECT            488
Name: 339, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           808
RELATION    similarTo
OBJECT            135
Name: 342, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT          1031
RELATION    similarTo
OBJECT            985
Name: 344, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           957
RELATION    similarTo
OBJECT            969
Name: 346, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            464
Name: 347, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           332
RELATION    similarTo
OBJECT            816
Name: 348, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           642
RELATION    similarTo
OBJECT            820
Name: 350, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT             9
RELATION    similarTo
OBJECT            853
Name: 351, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           860
RELATION    similarTo
OBJECT              4
Name: 353, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           808
RELATION    similarTo
OBJECT            756
Name: 354, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           802
RELATION    similarTo
OBJECT            348
Name: 357, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            508
Name: 358, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           358
RELATION    similarTo
OBJECT            846
Name: 359, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           309
RELATION    similarTo
OBJECT            805
Name: 362, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           869
RELATION    similarTo
OBJECT            251
Name: 366, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           860
RELATION    similarTo
OBJECT            491
Name: 368, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           849
RELATION    similarTo
OBJECT            931
Name: 369, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT            617
Name: 371, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           845
RELATION    similarTo
OBJECT            673
Name: 372, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            656
Name: 374, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           272
RELATION    similarTo
OBJECT            823
Name: 375, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            560
Name: 376, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           804
RELATION    similarTo
OBJECT            452
Name: 379, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            612
Name: 380, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           808
RELATION    similarTo
OBJECT            113
Name: 382, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           525
RELATION    similarTo
OBJECT            856
Name: 384, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           825
RELATION    similarTo
OBJECT            634
Name: 386, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           833
RELATION    similarTo
OBJECT            183
Name: 387, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT            603
Name: 389, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           976
RELATION    similarTo
OBJECT            996
Name: 390, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            716
Name: 391, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           656
RELATION    similarTo
OBJECT            846
Name: 392, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           817
RELATION    similarTo
OBJECT            661
Name: 393, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           859
RELATION    similarTo
OBJECT            622
Name: 394, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           852
RELATION    similarTo
OBJECT            465
Name: 395, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           873
RELATION    similarTo
OBJECT            783
Name: 396, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           834
RELATION    similarTo
OBJECT             26
Name: 397, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            210
Name: 398, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           489
RELATION    similarTo
OBJECT            798
Name: 399, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           869
RELATION    similarTo
OBJECT            297
Name: 400, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           713
RELATION    similarTo
OBJECT            818
Name: 402, dtype: object

-------------- POSITIVE SAMPLES
SUBJECT          1010
RELATION    similarTo
OBJECT            962
Name: 403, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           193
RELATION    similarTo
OBJECT            832
Name: 406, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           678
RELATION    similarTo
OBJECT            819
Name: 407, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            584
Name: 408, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           261
RELATION    similarTo
OBJECT            798
Name: 409, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            292
Name: 410, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           834
RELATION    similarTo
OBJECT            573
Name: 411, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           567
RELATION    similarTo
OBJECT            824
Name: 412, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            494
Name: 413, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           278
RELATION    similarTo
OBJECT            821
Name: 414, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           667
RELATION    similarTo
OBJECT            813
Name: 415, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           128
RELATION    similarTo
OBJECT            826
Name: 416, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           881
RELATION    similarTo
OBJECT            126
Name: 417, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           665
RELATION    similarTo
OBJECT            863
Name: 418, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           832
RELATION    similarTo
OBJECT            431
Name: 420, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           104
RELATION    similarTo
OBJECT            861
Name: 421, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           718
RELATION    similarTo
OBJECT            840
Name: 422, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           873
RELATION    similarTo
OBJECT            550
Name: 423, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           534
RELATION    similarTo
OBJECT            832
Name: 427, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           217
RELATION    similarTo
OBJECT            870
Name: 429, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           629
RELATION    similarTo
OBJECT            839
Name: 430, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           997
RELATION    similarTo
OBJECT            990
Name: 432, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           740
RELATION    similarTo
OBJECT            822
Name: 434, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           852
RELATION    similarTo
OBJECT            896
Name: 435, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           418
RELATION    similarTo
OBJECT            855
Name: 440, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           927
RELATION    similarTo
OBJECT            852
Name: 441, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            19
RELATION    similarTo
OBJECT            870
Name: 442, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            856
Name: 443, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            187
Name: 444, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           152
RELATION    similarTo
OBJECT            819
Name: 445, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           315
RELATION    similarTo
OBJECT            852
Name: 447, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            693
Name: 448, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           875
RELATION    similarTo
OBJECT            766
Name: 449, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           803
RELATION    similarTo
OBJECT            164
Name: 450, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           985
RELATION    similarTo
OBJECT            995
Name: 453, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           746
RELATION    similarTo
OBJECT            870
Name: 455, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           802
RELATION    similarTo
OBJECT            327
Name: 457, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            525
Name: 458, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           986
RELATION    similarTo
OBJECT           1028
Name: 459, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           833
RELATION    similarTo
OBJECT            767
Name: 460, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           397
RELATION    similarTo
OBJECT            808
Name: 461, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           533
RELATION    similarTo
OBJECT            835
Name: 464, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           965
RELATION    similarTo
OBJECT            960
Name: 465, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           845
RELATION    similarTo
OBJECT            476
Name: 468, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            392
Name: 469, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           871
RELATION    similarTo
OBJECT            905
Name: 470, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           802
RELATION    similarTo
OBJECT            590
Name: 473, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT            647
Name: 474, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           833
RELATION    similarTo
OBJECT            450
Name: 476, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           724
RELATION    similarTo
OBJECT            832
Name: 479, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           814
RELATION    similarTo
OBJECT            891
Name: 480, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           950
RELATION    similarTo
OBJECT            870
Name: 481, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            25
RELATION    similarTo
OBJECT            845
Name: 482, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            745
Name: 483, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           833
RELATION    similarTo
OBJECT            215
Name: 484, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           798
RELATION    similarTo
OBJECT            420
Name: 485, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           372
RELATION    similarTo
OBJECT            846
Name: 486, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           817
RELATION    similarTo
OBJECT            264
Name: 489, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT             0
RELATION    similarTo
OBJECT            818
Name: 490, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           885
RELATION    similarTo
OBJECT            725
Name: 492, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           615
RELATION    similarTo
OBJECT            856
Name: 493, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           861
RELATION    similarTo
OBJECT             86
Name: 494, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           820
RELATION    similarTo
OBJECT            732
Name: 495, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           456
RELATION    similarTo
OBJECT            852
Name: 496, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           813
RELATION    similarTo
OBJECT            428
Name: 497, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           703
RELATION    similarTo
OBJECT            863
Name: 498, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           878
RELATION    similarTo
OBJECT            344
Name: 500, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           815
RELATION    similarTo
OBJECT            732
Name: 501, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           875
RELATION    similarTo
OBJECT            167
Name: 502, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           982
RELATION    similarTo
OBJECT            962
Name: 503, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           814
RELATION    similarTo
OBJECT            537
Name: 504, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           850
RELATION    similarTo
OBJECT             97
Name: 505, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           851
RELATION    similarTo
OBJECT            414
Name: 507, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            374
Name: 508, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            99
RELATION    similarTo
OBJECT            851
Name: 511, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           832
RELATION    similarTo
OBJECT            592
Name: 513, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            930
Name: 514, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           856
RELATION    similarTo
OBJECT            524
Name: 515, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           825
RELATION    similarTo
OBJECT            322
Name: 516, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           820
RELATION    similarTo
OBJECT            920
Name: 517, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           860
RELATION    similarTo
OBJECT            818
Name: 518, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           873
RELATION    similarTo
OBJECT            753
Name: 519, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            29
RELATION    similarTo
OBJECT            869
Name: 520, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           861
RELATION    similarTo
OBJECT            339
Name: 521, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           813
RELATION    similarTo
OBJECT            461
Name: 522, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           226
RELATION    similarTo
OBJECT            860
Name: 523, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           813
RELATION    similarTo
OBJECT            799
Name: 524, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           840
RELATION    similarTo
OBJECT            572
Name: 525, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           960
RELATION    similarTo
OBJECT           1019
Name: 527, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           881
RELATION    similarTo
OBJECT            856
Name: 529, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            28
RELATION    similarTo
OBJECT            815
Name: 532, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           192
RELATION    similarTo
OBJECT            823
Name: 535, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT          1025
RELATION    similarTo
OBJECT           1015
Name: 536, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           287
RELATION    similarTo
OBJECT            823
Name: 537, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           504
RELATION    similarTo
OBJECT            818
Name: 538, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           172
RELATION    similarTo
OBJECT            840
Name: 539, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           269
RELATION    similarTo
OBJECT            815
Name: 540, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            41
RELATION    similarTo
OBJECT            855
Name: 541, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT            201
Name: 542, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           832
RELATION    similarTo
OBJECT            534
Name: 543, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           471
RELATION    similarTo
OBJECT            804
Name: 544, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            722
Name: 546, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           807
RELATION    similarTo
OBJECT            515
Name: 547, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           637
RELATION    similarTo
OBJECT            817
Name: 548, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            180
Name: 549, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           851
RELATION    similarTo
OBJECT            199
Name: 553, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           916
RELATION    similarTo
OBJECT            811
Name: 554, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           861
RELATION    similarTo
OBJECT            681
Name: 555, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           851
RELATION    similarTo
OBJECT             99
Name: 557, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           690
RELATION    similarTo
OBJECT            804
Name: 558, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           540
RELATION    similarTo
OBJECT            835
Name: 561, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           808
RELATION    similarTo
OBJECT            310
Name: 562, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           883
RELATION    similarTo
OBJECT            527
Name: 563, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           885
RELATION    similarTo
OBJECT            557
Name: 566, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           354
RELATION    similarTo
OBJECT            869
Name: 567, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            407
Name: 569, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           891
RELATION    similarTo
OBJECT            814
Name: 573, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           832
RELATION    similarTo
OBJECT            146
Name: 574, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           878
RELATION    similarTo
OBJECT            649
Name: 576, dtype: object

-------------- POSITIVE SAMPLES
SUBJECT            43
RELATION    similarTo
OBJECT            855
Name: 577, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           145
RELATION    similarTo
OBJECT            803
Name: 578, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           835
RELATION    similarTo
OBJECT            732
Name: 579, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           869
RELATION    similarTo
OBJECT            354
Name: 581, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           393
RELATION    similarTo
OBJECT            861
Name: 582, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           821
RELATION    similarTo
OBJECT            285
Name: 583, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           978
RELATION    similarTo
OBJECT            960
Name: 584, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT            83
RELATION    similarTo
OBJECT            808
Name: 585, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            950
Name: 587, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           860
RELATION    similarTo
OBJECT            226
Name: 588, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           848
RELATION    similarTo
OBJECT            360
Name: 590, dtype: object
-------------- POSITIVE SAMPLES
SUBJECT           878
RELATION    similarTo
OBJECT            195
Name: 591, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           876
RELATION    similarTo
OBJECT            570
Name: 9, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           866
RELATION    similarTo
OBJECT            917
Name: 13, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           884
RELATION    similarTo
OBJECT            156
Name: 19, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            222
Name: 21, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           800
RELATION    similarTo
OBJECT            621
Name: 24, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            470
Name: 25, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT          1012
RELATION    similarTo
OBJECT            964
Name: 27, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            904
Name: 30, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           281
RELATION    similarTo
OBJECT            801
Name: 36, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           835
RELATION    similarTo
OBJECT            132
Name: 38, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           882
RELATION    similarTo
OBJECT            429
Name: 40, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           809
RELATION    similarTo
OBJECT             32
Name: 41, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT             33
Name: 45, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            458
Name: 51, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            709
Name: 52, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           849
RELATION    similarTo
OBJECT            265
Name: 54, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           867
RELATION    similarTo
OBJECT            213
Name: 55, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           917
RELATION    similarTo
OBJECT            866
Name: 59, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           970
RELATION    similarTo
OBJECT           1012
Name: 63, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           884
RELATION    similarTo
OBJECT            462
Name: 66, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           238
RELATION    similarTo
OBJECT            879
Name: 67, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           801
RELATION    similarTo
OBJECT            389
Name: 69, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           579
RELATION    similarTo
OBJECT            844
Name: 71, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           827
RELATION    similarTo
OBJECT            893
Name: 74, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           823
RELATION    similarTo
OBJECT            890
Name: 76, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           809
RELATION    similarTo
OBJECT            758
Name: 78, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           849
RELATION    similarTo
OBJECT            554
Name: 79, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           804
RELATION    similarTo
OBJECT            275
Name: 88, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           862
RELATION    similarTo
OBJECT            564
Name: 91, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           800
RELATION    similarTo
OBJECT            507
Name: 94, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           539
RELATION    similarTo
OBJECT            857
Name: 95, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           833
RELATION    similarTo
OBJECT            239
Name: 99, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           802
RELATION    similarTo
OBJECT             50
Name: 100, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           884
RELATION    similarTo
OBJECT            676
Name: 102, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           441
RELATION    similarTo
OBJECT            866
Name: 106, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           838
RELATION    similarTo
OBJECT            242
Name: 107, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           868
RELATION    similarTo
OBJECT            490
Name: 113, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            455
Name: 114, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           849
RELATION    similarTo
OBJECT            604
Name: 115, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           835
RELATION    similarTo
OBJECT            467
Name: 119, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           966
RELATION    similarTo
OBJECT            962
Name: 121, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           835
RELATION    similarTo
OBJECT            427
Name: 123, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           574
RELATION    similarTo
OBJECT            854
Name: 125, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            738
Name: 130, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           410
RELATION    similarTo
OBJECT            857
Name: 133, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           378
RELATION    similarTo
OBJECT            800
Name: 141, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           880
RELATION    similarTo
OBJECT            874
Name: 145, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           885
RELATION    similarTo
OBJECT            232
Name: 146, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT            109
Name: 148, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT            23
RELATION    similarTo
OBJECT            830
Name: 150, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           962
RELATION    similarTo
OBJECT           1007
Name: 151, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            496
Name: 152, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT            20
RELATION    similarTo
OBJECT            868
Name: 158, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           871
RELATION    similarTo
OBJECT            578
Name: 163, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           801
RELATION    similarTo
OBJECT            840
Name: 166, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           859
RELATION    similarTo
OBJECT            160
Name: 167, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           831
RELATION    similarTo
OBJECT            576
Name: 168, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           885
RELATION    similarTo
OBJECT             72
Name: 199, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           810
RELATION    similarTo
OBJECT            591
Name: 205, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           835
RELATION    similarTo
OBJECT            427
Name: 213, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           881
RELATION    similarTo
OBJECT            271
Name: 215, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           823
RELATION    similarTo
OBJECT            159
Name: 216, dtype: object

--------------- NEGATIVE SAMPLES
SUBJECT           889
RELATION    similarTo
OBJECT            139
Name: 219, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           962
RELATION    similarTo
OBJECT            578
Name: 220, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            918
Name: 221, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           810
RELATION    similarTo
OBJECT            757
Name: 222, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           865
RELATION    similarTo
OBJECT            399
Name: 223, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           884
RELATION    similarTo
OBJECT            676
Name: 225, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           836
RELATION    similarTo
OBJECT            196
Name: 228, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           865
RELATION    similarTo
OBJECT            581
Name: 230, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           857
RELATION    similarTo
OBJECT            736
Name: 231, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           824
RELATION    similarTo
OBJECT            486
Name: 235, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           666
RELATION    similarTo
OBJECT            827
Name: 236, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           857
RELATION    similarTo
OBJECT             46
Name: 237, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           854
RELATION    similarTo
OBJECT            154
Name: 238, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT            641
Name: 243, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           821
RELATION    similarTo
OBJECT            119
Name: 244, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           962
RELATION    similarTo
OBJECT            185
Name: 252, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           865
RELATION    similarTo
OBJECT            619
Name: 253, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           823
RELATION    similarTo
OBJECT            674
Name: 254, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           824
RELATION    similarTo
OBJECT            934
Name: 260, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           834
RELATION    similarTo
OBJECT            273
Name: 262, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           811
RELATION    similarTo
OBJECT            810
Name: 265, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           396
RELATION    similarTo
OBJECT            800
Name: 266, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           824
RELATION    similarTo
OBJECT            219
Name: 268, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           872
RELATION    similarTo
OBJECT             35
Name: 269, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT            71
RELATION    similarTo
OBJECT            816
Name: 272, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           862
RELATION    similarTo
OBJECT            564
Name: 274, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           854
RELATION    similarTo
OBJECT            362
Name: 275, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           838
RELATION    similarTo
OBJECT            196
Name: 277, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           872
RELATION    similarTo
OBJECT            829
Name: 279, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           825
RELATION    similarTo
OBJECT             52
Name: 286, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           803
RELATION    similarTo
OBJECT             50
Name: 287, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT             71
Name: 288, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           268
RELATION    similarTo
OBJECT            865
Name: 289, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           811
RELATION    similarTo
OBJECT             70
Name: 290, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT            421
Name: 293, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT            641
Name: 298, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           885
RELATION    similarTo
OBJECT            232
Name: 300, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            222
Name: 302, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT             61
Name: 305, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           879
RELATION    similarTo
OBJECT            321
Name: 306, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           804
RELATION    similarTo
OBJECT            275
Name: 312, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           855
RELATION    similarTo
OBJECT            262
Name: 314, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           993
RELATION    similarTo
OBJECT            904
Name: 316, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            324
Name: 317, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           907
RELATION    similarTo
OBJECT            827
Name: 319, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT          1012
RELATION    similarTo
OBJECT            979
Name: 321, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           806
RELATION    similarTo
OBJECT            951
Name: 325, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT            163
Name: 332, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT          1037
RELATION    similarTo
OBJECT            962
Name: 334, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           889
RELATION    similarTo
OBJECT             51
Name: 337, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            200
Name: 338, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           865
RELATION    similarTo
OBJECT            399
Name: 340, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           843
RELATION    similarTo
OBJECT            371
Name: 341, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           862
RELATION    similarTo
OBJECT            349
Name: 343, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT          1004
RELATION    similarTo
OBJECT           1012
Name: 345, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           815
RELATION    similarTo
OBJECT            655
Name: 349, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           207
RELATION    similarTo
OBJECT            857
Name: 352, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           887
RELATION    similarTo
OBJECT             74
Name: 355, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           884
RELATION    similarTo
OBJECT            565
Name: 356, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           874
RELATION    similarTo
OBJECT            355
Name: 360, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           845
RELATION    similarTo
OBJECT            243
Name: 361, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           443
RELATION    similarTo
OBJECT            876
Name: 363, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           886
RELATION    similarTo
OBJECT            580
Name: 364, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           707
RELATION    similarTo
OBJECT            801
Name: 365, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           462
RELATION    similarTo
OBJECT            884
Name: 367, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           868
RELATION    similarTo
OBJECT             79
Name: 370, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           823
RELATION    similarTo
OBJECT            102
Name: 373, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           854
RELATION    similarTo
OBJECT            116
Name: 377, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           876
RELATION    similarTo
OBJECT            570
Name: 378, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           833
RELATION    similarTo
OBJECT            239
Name: 381, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           825
RELATION    similarTo
OBJECT             52
Name: 383, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT            69
RELATION    similarTo
OBJECT            886
Name: 385, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT          1028
RELATION    similarTo
OBJECT            941
Name: 388, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           962
RELATION    similarTo
OBJECT            966
Name: 401, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           867
RELATION    similarTo
OBJECT            416
Name: 404, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           816
RELATION    similarTo
OBJECT            887
Name: 405, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT            738
Name: 419, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           852
RELATION    similarTo
OBJECT            150
Name: 424, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           849
RELATION    similarTo
OBJECT            185
Name: 425, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           862
RELATION    similarTo
OBJECT            302
Name: 426, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           929
RELATION    similarTo
OBJECT            827
Name: 428, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           806
RELATION    similarTo
OBJECT            424
Name: 431, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           857
RELATION    similarTo
OBJECT             46
Name: 433, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           885
RELATION    similarTo
OBJECT             72
Name: 436, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           851
RELATION    similarTo
OBJECT            314
Name: 437, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           855
RELATION    similarTo
OBJECT            312
Name: 438, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           868
RELATION    similarTo
OBJECT            120
Name: 439, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           876
RELATION    similarTo
OBJECT            443
Name: 446, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           960
RELATION    similarTo
OBJECT           1000
Name: 451, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           884
RELATION    similarTo
OBJECT            770
Name: 452, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           836
RELATION    similarTo
OBJECT            835
Name: 454, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           997
RELATION    similarTo
OBJECT           1032
Name: 456, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           729
RELATION    similarTo
OBJECT            830
Name: 462, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           839
RELATION    similarTo
OBJECT            496
Name: 463, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           830
RELATION    similarTo
OBJECT             23
Name: 466, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           877
RELATION    similarTo
OBJECT            640
Name: 467, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           874
RELATION    similarTo
OBJECT            403

Name: 471, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           811
RELATION    similarTo
OBJECT            901
Name: 472, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           960
RELATION    similarTo
OBJECT           1000
Name: 475, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           846
RELATION    similarTo
OBJECT            458
Name: 477, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           867
RELATION    similarTo
OBJECT            926
Name: 478, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           290
RELATION    similarTo
OBJECT            854
Name: 487, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           997
RELATION    similarTo
OBJECT           1032
Name: 488, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           545
RELATION    similarTo
OBJECT            854
Name: 491, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           877
RELATION    similarTo
OBJECT            181
Name: 499, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           962
RELATION    similarTo
OBJECT           1020
Name: 506, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            224
Name: 509, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           857
RELATION    similarTo
OBJECT            687
Name: 510, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           874
RELATION    similarTo
OBJECT            171
Name: 512, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           831
RELATION    similarTo
OBJECT            353
Name: 526, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           876
RELATION    similarTo
OBJECT            747
Name: 528, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT          1028
RELATION    similarTo
OBJECT            960
Name: 530, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           826
RELATION    similarTo
OBJECT            324
Name: 531, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           805
RELATION    similarTo
OBJECT            224
Name: 533, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           353
RELATION    similarTo
OBJECT            831
Name: 534, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           893
RELATION    similarTo
OBJECT            827
Name: 545, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           271
RELATION    similarTo
OBJECT            881
Name: 550, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           235
RELATION    similarTo
OBJECT            830
Name: 551, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           660
RELATION    similarTo
OBJECT            866
Name: 552, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT          1028
RELATION    similarTo
OBJECT            904
Name: 556, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           821
RELATION    similarTo
OBJECT            119
Name: 559, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           861
RELATION    similarTo
OBJECT            454
Name: 560, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           811
RELATION    similarTo
OBJECT            938
Name: 564, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           801
RELATION    similarTo
OBJECT            707
Name: 565, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           799
RELATION    similarTo
OBJECT             61
Name: 568, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           889
RELATION    similarTo
OBJECT            487
Name: 570, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           962
RELATION    similarTo
OBJECT           1037
Name: 571, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           844
RELATION    similarTo
OBJECT            366
Name: 572, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           806
RELATION    similarTo
OBJECT            933
Name: 575, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           870
RELATION    similarTo
OBJECT            874
Name: 580, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           709
RELATION    similarTo
OBJECT            830
Name: 586, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           867
RELATION    similarTo
OBJECT             27
Name: 589, dtype: object
--------------- NEGATIVE SAMPLES
SUBJECT           810
RELATION    similarTo
OBJECT            712
Name: 592, dtype: object

Features : 'LEGAL_DESIGN', 'LEGAL_PATENT', 'LEGAL_TRADEMARK', 'LEGAL_COPYRIGHT', 'COPYRIGHT_ACT', 'PATENTS_ACT', 'DESIGNS_ACT', 'TRADEMARK_ACT'

Number of Features : 8

AUC Score in 600 epochs : 0.6274446648973178

Features : 'LEGAL_DESIGN', 'LEGAL_PATENT', 'LEGAL_TRADEMARK', 'LEGAL_COPYRIGHT', 'LAW', 'INFRINGEMENT', 'COPYRIGHT_ACT', 'PATENTS_ACT', 'DESIGNS_ACT', 'TRADEMARK_ACT'

Number of Features : 10

AUC Score in 600 epochs : 0.4870648560900822

Features : 
'LEGAL_SCJUDGE'
'LEGAL_DESIGN'
'LEGAL_GEN'
'LEGAL_PATENT'
'LEGAL_TRADEMARK'
'LEGAL_COPYRIGHT', 'LEGAL_RESERVATION_CATEGORY', 'LEGAL_CRIMINAL_PROCEDURE', 'LEGAL_ENTITY', 'LAW', 'INFRINGEMENT', 'PERSON', 'NATION/RELIGIOUS/POL_GROUP', 'GEOGRAPHICAL_LOC', 'LANGUAGE', 'LOCATION_STRUCTURE', 'LOCATION', 'CONTACTNAME', 'ORGANIZATION', 'ORGANIZATION2', 'GEOGRAPHY2', 'DATETIME', 'PERCENT', 'COPYRIGHT_ACT', 'PATENTS_ACT', 'DESIGNS_ACT', 'INFORMATION_TECHNOLOGY_ACT', 'TRADEMARK_ACT'

Number of Features : 27

AUC Score in 600 epochs : 0.5558375634517766

Features : 
'LEGAL_SCJUDGE'
'LEGAL_DESIGN'
'LEGAL_GEN'
'LEGAL_PATENT'
'LEGAL_TRADEMARK'
'LEGAL_COPYRIGHT'
'LEGAL_RESERVATION_CATEGORY'
'LEGAL_CRIMINAL_PROCEDURE'
'LEGAL_ENTITY'
'COPYRIGHT_ACT'
'PATENTS_ACT'
'DESIGNS_ACT'
'INFORMATION_TECHNOLOGY_ACT'
'TRADEMARK_ACT'

Number of Features : 14

AUC Score in 600 epochs : 0.6271978592289471

Flow of the program

Input: 
1. OE_LABELS(csv file) : contains features of the nodes
2. MAPPING.json : maps the document ids to node ids
3. TRAIN_SET(csv) : contains data in triples format where each row indicates an edge (docid,similarTo,docid)
4. TEST_SET(csv) : contains data in triples format where each row indicates an edge (docid,similarTo,docid)

Flow(as understood)
1. Create a heterograph of train set
2. Create a heterograph of test set
3. Perform negative sampling in both the graphs
4. Initialize RGCN model and pass parameters
5. Train the model on using the train graph with negative edges as well
6. Test the model using the TEST_SET
7. Compute AUC score
8. Compute the probabilities of similarity between two nodes in an edge
9. Parse this probability array
    if prob. is greater than average(prob.)
        keep in predicted results
    else
        keep in non predicted results