In [1]:
import pandas as pd
import numpy as np

In [2]:
oe = pd.read_csv("OE_LABELS.csv")

In [3]:
ner = pd.read_csv("NER_FEATURES.csv")

In [4]:
oe

,tid,LEGAL_SCJUDGE,LEGAL_DESIGN,LEGAL_GEN,LEGAL_PATENT,LEGAL_TRADEMARK,LEGAL_COPYRIGHT,LEGAL_RESERVATION_CATEGORY,LEGAL_CRIMINAL_PROCEDURE,LEGAL_ENTITY,COPYRIGHT_ACT,PATENTS_ACT,DESIGNS_ACT,INFORMATION_TECHNOLOGY_ACT,TRADEMARK_ACT
0,100123,0,6,17,0,0,0,0,209,10,0,0,0,0,0
1,1001948,0,4,31,2,0,5,4,66,10,1,0,0,0,0
2,1006468,0,4,31,0,3,0,0,191,17,0,0,0,0,0
3,1006709,0,0,22,0,0,0,0,66,1,0,0,0,0,0
4,1007946,0,0,17,0,0,3,0,66,17,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,81162651,0,6,26,0,0,0,0,14,17,0,0,0,0,0
1034,8433581,0,8,2,0,62,5,4,209,10,1,0,0,0,0
1035,850381,0,4,31,3,62,0,5,191,17,0,0,0,0,0
1036,94612663,0,4,31,0,62,0,4,66,17,0,0,0,0,1
1037,98291024,0,0,31,0,0,0,0,54,6,0,0,0,0,0

In [5]:
ner

,tid,LAW,INFRINGEMENT,PERSON,NATION/RELIGIOUS/POL_GROUP,GEOGRAPHICAL_LOC,LANGUAGE,LOCATION_STRUCTURE,LOCATION,CONTACTNAME,ORGANIZATION,ORGANIZATION2,GEOGRAPHY2,DATETIME,PERCENT
0,1004544,0,0,0,0,1341,0,0,24623,0,128404,0,277,0,0
1,102042281,0,1,0,0,1337,0,0,24825,0,128740,0,277,0,0
2,1025815,0,1,0,0,1286,0,0,24972,0,128600,0,277,0,0
3,1062207,0,1,0,0,1257,0,0,24815,0,127847,0,277,0,0
4,106681665,0,1,0,0,1264,0,0,24595,0,128426,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,99622088,58915,0,8817,868,1351,0,24825,24556,0,71755,128694,277,0,0
1034,996328,47882,0,32717,730,1358,26,11327,24564,0,122994,126885,277,0,0
1035,996348,61064,0,19129,1144,1286,0,23872,6178,0,67548,84493,277,0,0
1036,99670896,56497,0,40157,0,1351,0,24825,24556,0,52834,128902,277,0,0
1037,997135,37952,0,4505,0,795,0,17802,19287,0,128426,128644,276,0,0

In [6]:
oe_t = oe.sort_values(by=['tid'])

In [7]:
ner_t = ner.sort_values(by=['tid'])

In [8]:
oe_t

,tid,LEGAL_SCJUDGE,LEGAL_DESIGN,LEGAL_GEN,LEGAL_PATENT,LEGAL_TRADEMARK,LEGAL_COPYRIGHT,LEGAL_RESERVATION_CATEGORY,LEGAL_CRIMINAL_PROCEDURE,LEGAL_ENTITY,COPYRIGHT_ACT,PATENTS_ACT,DESIGNS_ACT,INFORMATION_TECHNOLOGY_ACT,TRADEMARK_ACT
282,1566,0,7,2,2,0,0,0,66,16,0,0,0,0,0
645,4354,0,7,30,0,0,0,0,191,16,0,0,0,0,0
696,5192,0,6,33,3,0,0,0,66,17,0,0,0,0,0
767,6547,0,7,30,0,0,3,5,191,21,0,0,0,0,0
973,13352,0,4,31,0,0,0,0,209,10,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000,192230665,0,4,17,2,62,26,4,191,17,0,0,0,0,0
480,192914986,0,0,0,0,0,0,0,66,15,0,0,0,0,0
485,194456776,0,7,17,0,0,0,4,191,8,0,0,0,0,0
504,198827109,0,0,31,0,0,19,0,14,17,0,0,0,0,0
509,199908142,0,7,31,0,0,3,4,66,17,0,0,0,0,0

In [9]:
ner_t

,tid,LAW,INFRINGEMENT,PERSON,NATION/RELIGIOUS/POL_GROUP,GEOGRAPHICAL_LOC,LANGUAGE,LOCATION_STRUCTURE,LOCATION,CONTACTNAME,ORGANIZATION,ORGANIZATION2,GEOGRAPHY2,DATETIME,PERCENT
375,1566,52476,0,7427,1033,1358,0,16793,24564,0,79988,6235,277,0,0
732,4354,73493,0,9487,267,1286,44,24815,6268,0,50100,75502,294,0,0
782,5192,72155,0,10253,41,297,44,4994,12571,0,127202,56200,276,0,0
848,6547,68185,0,26578,1210,1249,44,24597,20419,0,127202,128644,58,0,0
18,13352,0,0,0,0,0,0,0,24875,0,128667,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,192230665,0,1,0,0,1341,0,0,24815,0,127506,0,277,0,0
569,192914986,0,0,25976,0,1341,0,14290,5038,0,127433,118077,277,0,0
574,194456776,20541,0,5050,1144,1279,0,8400,15386,0,119194,89049,277,0,0
593,198827109,69808,0,20021,931,800,44,24959,14710,0,128162,64481,250,0,0
598,199908142,74224,0,4750,0,1286,0,1654,5994,0,62499,18699,252,0,0

In [10]:
oe_t.to_csv("OE_WITHOUT_NER_SORTED.csv",index=False)

In [11]:
ner_t.to_csv("OE_NER_SORTED.csv",index=False)

In [15]:
df3 = pd.merge(oe_t, ner_t, on = 'tid')

In [16]:
df3

,tid,LEGAL_SCJUDGE,LEGAL_DESIGN,LEGAL_GEN,LEGAL_PATENT,LEGAL_TRADEMARK,LEGAL_COPYRIGHT,LEGAL_RESERVATION_CATEGORY,LEGAL_CRIMINAL_PROCEDURE,LEGAL_ENTITY,...,GEOGRAPHICAL_LOC,LANGUAGE,LOCATION_STRUCTURE,LOCATION,CONTACTNAME,ORGANIZATION,ORGANIZATION2,GEOGRAPHY2,DATETIME,PERCENT
0,1566,0,7,2,2,0,0,0,66,16,...,1358,0,16793,24564,0,79988,6235,277,0,0
1,4354,0,7,30,0,0,0,0,191,16,...,1286,44,24815,6268,0,50100,75502,294,0,0
2,5192,0,6,33,3,0,0,0,66,17,...,297,44,4994,12571,0,127202,56200,276,0,0
3,6547,0,7,30,0,0,3,5,191,21,...,1249,44,24597,20419,0,127202,128644,58,0,0
4,13352,0,4,31,0,0,0,0,209,10,...,0,0,0,24875,0,128667,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,192230665,0,4,17,2,62,26,4,191,17,...,1341,0,0,24815,0,127506,0,277,0,0
1034,192914986,0,0,0,0,0,0,0,66,15,...,1341,0,14290,5038,0,127433,118077,277,0,0
1035,194456776,0,7,17,0,0,0,4,191,8,...,1279,0,8400,15386,0,119194,89049,277,0,0
1036,198827109,0,0,31,0,0,19,0,14,17,...,800,44,24959,14710,0,128162,64481,250,0,0
1037,199908142,0,7,31,0,0,3,4,66,17,...,1286,0,1654,5994,0,62499,18699,252,0,0

In [17]:
df3.columns

Index(['tid', 'LEGAL_SCJUDGE', 'LEGAL_DESIGN', 'LEGAL_GEN', 'LEGAL_PATENT',
       'LEGAL_TRADEMARK', 'LEGAL_COPYRIGHT', 'LEGAL_RESERVATION_CATEGORY',
       'LEGAL_CRIMINAL_PROCEDURE', 'LEGAL_ENTITY', 'COPYRIGHT_ACT',
       'PATENTS_ACT', 'DESIGNS_ACT', 'INFORMATION_TECHNOLOGY_ACT',
       'TRADEMARK_ACT', 'LAW', 'INFRINGEMENT', 'PERSON',
       'NATION/RELIGIOUS/POL_GROUP', 'GEOGRAPHICAL_LOC', 'LANGUAGE',
       'LOCATION_STRUCTURE', 'LOCATION', 'CONTACTNAME', 'ORGANIZATION',
       'ORGANIZATION2', 'GEOGRAPHY2', 'DATETIME', 'PERCENT'],
      dtype='object')

In [18]:
df3.to_csv("FINAL_OE_LABELS_WITH_NER.csv",index=False)

In [8]:
int(100123.0)

100123

In [12]:
import pandas as pd

In [13]:
f = pd.read_csv("BERT_FEATURES_AVERAGE.csv")
for i in range(f.shape[0]):
    x = int(f.iloc[i,0])
    print(x)
    f.iloc[i,0] = int(x)

f.to_csv("BERT_FEATURES.csv",index=False)

100123
1001948
1006468
1006709
1007946
101008236
1011356
1012649
1013766
1014138
1019490
1022090
1022584
1023674
10239019
1024124
102653512
102852
102886851
103057287
1030976
1033637
1033812
103434922
1035346
103561
1035719
1038563
104312764
104313664
104377
104810373
1048632
104935066
1052178
1053542
1056935
105936170
1062099
1073828
107853771
108020655
108509106
1086058
1092394
109700315
1097490
1097981
1098305
109874394
1099140
1102062
1103984
1104087
1104701
1105134
1106747
110813550
1110013
1114158
1115541
111777378
1120137
1120277
1120373
1121229
112850760
112896520
112937069
1129833
1130742
1131957
1132299
1132362
1134429
1134697
1136663
1136885
113963352
1147125
1147963
1149874
1151918
1152518
1154981
1155640
1156538
115701246
115718142
1159790
1163546
116548206
1165503
1166220
1168060
1180101
1180206
1180216
118046405
1181080
118501220
1186368
1186410
1187885
1187886
119316583
1194654
119540048
1195618
1199558
1202878
120358
12050516
1206754
1206795
1209528
1212077
1213021
1213194
1214980
1216757
1220952
122362
1224686
1231223
1231997
1233360
1233850
123737198
1237504
1239673
1240131
124137051
1242789
1246653
1247926
1261492
126699
1271015
1274327
127517806
1276331
1278222
1278868
1281050
128161
1287305
1290723
1291316
1292071
1292463
1295746
1296255
1297488
1299452
1300072
1300646
1300681
130087
130353321
1304475
130470
1307266
1307808
1313207
1318646
1319506
1326449
1326478
1326499
1327080
1328814
1329151
1330629
1333219
1334665
1335881
133640019
1338327
1338837
1341112
1341716
1341895
134913
1350547
135285745
1353689
1354608
1355660
135809
135953
1362442
1363234
1365277
137050
137238378
1375132
1377335
137734242
1378876
138184
138192511
1381953
138217214
1382657
1382698
138826371
1389940
139299795
139670361
1397964
1401520
1401567
1403309
1403823
1404351
1405951
1407895
1411268
1414629
1415114
1416283
1418391
1425094
1425329
1425907
1426304
143202244
14377547
1438183
143917974
1439704
1440160
1442144
1445734
1447296
1453719
145401736
1462242
146267
1465670
146940961
1470887
1474119
1475926
148082701
1482259
1483262
1484358
1486034
1486949
1487019
14898186
1500505
150473
1505859
1507797
150814946
1508554
1509628
151308629
1514111
1514512
1515299
151609698
1519371
1521407
1521460
152460
1528386
1536230
1537954
1543503
1543623
1548289
154833956
1550190
155272316
155329262
1555192
155579055
1564015
1566
1567371
1567797
1568935
1572876
1576587
1578200
1584936
1586918
1589218
1592558
1593570
1594031
1596320
1596866
1597179
1599972
160205361
1602137
1602162
1604568
1610804
161147300
1611623
1611775
1615016
161614515
1616148
161939
162420
162432291
1627481
162878090
1629830
1630167
1633179
163696803
164002734
1640744
1641452
1643138
1643349
1648254
165099707
1655935
165621647
1656601
165776436
165968354
1659850
166007515
1660833
1662395
1663733
1664373
166780307
1668065
1668551
1669803
1671648
1672214
167333165
1674695
1677837
1677896
16810704
1682715
168489488
1685319
1695101
169522737
1695291
1697217
1700195
1703545
1706612
170697
1714313
1716282
1718159
1719469
1722050
1723469
172383107
1725672
1727525
1732220
1732339
1732840
1734007
1735815
1737054
1738256
1738333
1741822
1741949
1742704
1747577
1747781
174974
1750914
175175391
175238601
1752565
1754074
175829
176039345
176122260
1763149
1763592
176508424
1765871
1766147
1766312
1767393
1771122
1771435
1771880
17789938
178445
179477870
179794777
179814250
1798615
1799441
1802196
1805387
1806604
180850491
181033
1813801
181459283
1815080
181654439
1817694
1822024
1830927
1831036
1831078
183120061
183600564
1836621
183717026
183868316
183984262
1844910
184660633
1847057
1850663
18546
1856009
1857950
1861080
1866073
1867924
1869228
1869992
1874558
187501619
1876565
187706
1877462
1877641
1877956
1878548
1881313
1882267
188348
1883538
188357431
188429772
1885635
1887773
188958994
1890740
1890994
1891895
189337794
1899039
189907
1900118
1901943
190196010
1902038
1903089
1905157
1907642
1907957
1911637
1916388
191721813
191907197
1919561
1920837
1923487
1926500
19267666
1928398
192914986
1938230
1938862
1939993
1940266
194456776
1947054
1951505
1954356
1956673
1959866
195994
1960330
1960340
1961394
1963322
1965204
1965879
1967742
1969682
1979794
1981010
1986616
1986966
198827109
1988625
1988649
1989264
1991497
199908142
1999324
1999671
199977
20356733
2044127
204742
206804
211970
212274
213382
21369704
214713
220229
222788
223504
224777
227988
231341
23402471
23954109
241970
243002
246887
248715
249589
256224
257876
258508
261992
263884
264657
2671204
26718353
268937
271216
27152913
275246
27773000
279427
279466
280042
280485
280498
281850
28356393
288525
29023706
290385
290962
292146
292286
292442
293197
296025
30319311
306336
306833
307021
309271
309307
309541
310087
3111930
31239895
314044
315432
315836
31621011
317172
3173546
317554
323576
328927
329158
330608
331232
33136745
33194727
332955
334293
338008
338115
341560
342903
344644
347224
350457
350628
350976
353578
353751
354829
357132
363089
368264
36875
36937
371933
374340
37494799
37721629
377266
379222
37934
37963
37987
380655
382721
383397
3849421
386457
38764718
39169380
391843
39217891
396205
39679
399708
403501
40533940
407511
40753175
410114
414792
415294
41554823
421030
422732
42294818
42299665
42355707
424874
425153
429924
43335747
4354
435765
437533
442517
44410582
444303
444914
446174
44641638
446828
450219
452434
453977
455122
456839
458739
465681
467194
468834
471272
47391891
474885
476474
477104
477313
47808634
48216667
483734
483899
486081
487303
491934
492853
494408
49480
499867
50089303
501542
507033
508915
509065
5114588
511635
511784
511928
512761
513801
514077
514933
51545606
51689837
5192
52129591
524871
525017
528391
529229
529384
53080
5398766
540642
54865315
54995969
55517912
557368
557776
56087922
565540
565788
574884
57555980
576454
57798471
579822
58263027
582634
584252
584977
585040
585219
588099
590022
591481
594383
600280
603848
605322
60799
611025
612964
6137338
614536
614998
615459
617044
617728
619152
620033
620904
623061
623494
625240
627069
629330
62991042
630125
63283859
633111
634059
634160
634266
63489929
639803
64231867
64332
647343
65151197
651705
652828
65293457
653417
6544121
6547
657557
659090
66104323
665756
668225
67143323
67255
672966
673012
678038
67892682
681372
681713
681866
68469
685234
686582
687034
68799740
69052901
691481
693281
693363
693891
69624144
699319
7003391
70037708
703764
70463837
70487596
707249
710165
712132
712415
71315
713825
730804
732612
733192
735457
73583860
736105
73767384
74028
74061245
743158
743328
74910860
753224
75646
756739
757639
759618
761967
762055
762574
762747
76636976
769115
769926
774102
784265
784749
789627
7926018
79280249
793348
793618
794450
794815
794955
795465
79561
800341
80498353
805786
80997184
810279
81086651
816271
816411
81716407
81824666
819445
820931
821579
82620
82895350
832781
833158
83406
83741552
837614
838466
843614
844819
849254
850428
850597
850821
85089691
85467018
856194
857323
85777093
858066
858492
860600
861349
861510
864375
865758
866760
867423
86762634
86904342
869781
871220
873775
875590
877389
877414
880032
88087196
883586
88397
885778
890637
89164
891864
8919089
893844
894494
89564
896743
896874
899181
899744
899938
904832
907493
910213
91088
911084
912526
913118
91635
919121
919241
91986422
925897
928322
93127
936398
936707
938898
939624
941137
943008
94514
946842
94788795
950361
952082
952963
952975
955097
96002
962370
963790
96706
968805
96932
973363
977497
980877
982330
98342524
985842
98622476
988645
992249
994554
995861
99622088
996328
996348
99670896
997135
1004544
102042281
1025815
1062207
106681665
1118022
112995556
1165153
117903
1202388
1238420
1269197
1281453
1300598
1306228
13352
136111
1375229
139585580
141920684
14349
145549327
1460395
147470112
1502681
1509899
152715128
1557873
157791679
1611564
1640143
1657978
170719338
1741869
1784548
1789265
179972913
18135822
181424088
1857898
1864885
1900841
192230665
1945028
19504407
1965135
1981161
1983225
27816811
304538
321682
3304039
340501
357841
374690
42490190
49386818
52700318
60866758
614155
618763
645115
646292
663392
67204010
6896400
691314
700020
70200400
73989
744316
767356
78472331
788484
8022081
81162651
8433581
850381
94612663
98291024